### ISSUE TITLE
Firefox的contenteditable光标异常

### ISSUE THREAD

**Issue by fangkuairen-steve** [blacktunes/sr-message-maker#2]
_使用环境：网页https://sr.shenmedouyou.top/ 系统环境windows11家庭中文版22H2build insider23475.1000/浏览器MozillaFirefox114.0.1(64bit)_
## 问题：在群聊标题栏使用微软拼音输入时仅会输入首个字母，如输入 “三月七(san'yue'qi)"仅显示s(如图）
![图片](https://github.com/blacktunes/sr-message-maker/assets/106574500/b5ce3c47-0830-49f3-8a33-1f98fee95c20)
---
## 可能的问题诱因
在使用的过程中，发现群聊标题栏在输入文字的时候光标在输入每一个字符后会自动弹回输入框首
如
要输入的文本：March 7th
光标位置：
1.|
2.|M       （输入M)
3.M|       (手动移动光标至M后）
4.|Ma    (输入a)
......

**Comment by blacktunes** [comment]
是Firefox的问题，滚动条也有问题
过几天我再改
