### ISSUE TITLE
建议添加长图导出

### ISSUE THREAD

**Issue by Vivian-Xie** [blacktunes/sr-message-maker#28]
好棒的制作！但是想要生成小短片以外的图片的话就得一点点截图，观感不太好，盼望完善！

**Comment by blacktunes** [comment]
![save](https://github.com/blacktunes/sr-message-maker/assets/38934611/a3f2470e-04bc-4b00-968a-b6ae7784d132)
播放按钮隔壁就有个保存按钮，你直接`CTRL+S`也行

**Comment by Vivian-Xie** [comment]
噢噢噢噢是我的弹窗拦截了！不好意思！看到按钮了！
