### ISSUE TITLE
内容超过一行时，气泡框「光阴莫负」会被不正确地拉长

### ISSUE THREAD

**Issue by tomokaitoh** [blacktunes/sr-message-maker#45]
如图，气泡框左上角的三月七图标和右下角的奶茶图标都被拉长了。
![7d6050d521cc32a952ebf0df71e42f7d](https://github.com/user-attachments/assets/01891810-937c-4265-b601-bf2035e4168a)

**Comment by blacktunes** [comment]
懒得大改了，把图案缩一下算了
