### ISSUE TITLE
灵砂后面的角色还会更新吗

### ISSUE THREAD

**Issue by AS-N70** [blacktunes/sr-message-maker#49]
首先作者辛苦了！
然后就是看到短信生成器目前角色只更新到灵砂，后面的角色还没有，想问下大佬还会更新吗

**Comment by blacktunes** [comment]
最近实在太忙了，我找时间更一下吧
有自定义角色功能，没更新的角色可以自己创一个

**Comment by AS-N70** [comment]
好的~大佬辛苦啦
